export const STELLAR_CONFIG = {
  NETWORK: 'testnet',
  HORIZON_URL: 'https://horizon-testnet.stellar.org',
  CONTRACTS: {
    FUND_TOKEN: 'CCLU7JCLZ7A4ZNUM46GLOBERIQ4QN36SCFTPXQH6KZCE4NBSUTFVLYXY',
    RECEIVABLE_VAULT: 'CCFMTLYIEQLQ44NQM4XBXVOACEC66WTDL5LLV57O2FUYTFQYURWLRBLN'
  },
  ADMIN_ADDRESS: 'GCLCDXUFX7HRML3VXY3F2JM2LJ3OI565UEFZ4EJVJYHFFALXWYKX2XGN'
};